//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientesoap.ServicioSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://DefaultNamespace", ConfigurationName="ServicioSOAP.SoapService")]
    public interface SoapService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://DefaultNamespace no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        clientesoap.ServicioSOAP.validarrutResponse validarrut(clientesoap.ServicioSOAP.validarrutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<clientesoap.ServicioSOAP.validarrutResponse> validarrutAsync(clientesoap.ServicioSOAP.validarrutRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombres del espacio de nombres http://DefaultNamespace no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        clientesoap.ServicioSOAP.nombrepropioResponse nombrepropio(clientesoap.ServicioSOAP.nombrepropioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<clientesoap.ServicioSOAP.nombrepropioResponse> nombrepropioAsync(clientesoap.ServicioSOAP.nombrepropioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarrutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarrut", Namespace="http://DefaultNamespace", Order=0)]
        public clientesoap.ServicioSOAP.validarrutRequestBody Body;
        
        public validarrutRequest() {
        }
        
        public validarrutRequest(clientesoap.ServicioSOAP.validarrutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DefaultNamespace")]
    public partial class validarrutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        public validarrutRequestBody() {
        }
        
        public validarrutRequestBody(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarrutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarrutResponse", Namespace="http://DefaultNamespace", Order=0)]
        public clientesoap.ServicioSOAP.validarrutResponseBody Body;
        
        public validarrutResponse() {
        }
        
        public validarrutResponse(clientesoap.ServicioSOAP.validarrutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DefaultNamespace")]
    public partial class validarrutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validarrutReturn;
        
        public validarrutResponseBody() {
        }
        
        public validarrutResponseBody(string validarrutReturn) {
            this.validarrutReturn = validarrutReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nombrepropioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nombrepropio", Namespace="http://DefaultNamespace", Order=0)]
        public clientesoap.ServicioSOAP.nombrepropioRequestBody Body;
        
        public nombrepropioRequest() {
        }
        
        public nombrepropioRequest(clientesoap.ServicioSOAP.nombrepropioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DefaultNamespace")]
    public partial class nombrepropioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellidopa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellidoma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sexo;
        
        public nombrepropioRequestBody() {
        }
        
        public nombrepropioRequestBody(string nombres, string apellidopa, string apellidoma, string sexo) {
            this.nombres = nombres;
            this.apellidopa = apellidopa;
            this.apellidoma = apellidoma;
            this.sexo = sexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nombrepropioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nombrepropioResponse", Namespace="http://DefaultNamespace", Order=0)]
        public clientesoap.ServicioSOAP.nombrepropioResponseBody Body;
        
        public nombrepropioResponse() {
        }
        
        public nombrepropioResponse(clientesoap.ServicioSOAP.nombrepropioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://DefaultNamespace")]
    public partial class nombrepropioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombrepropioReturn;
        
        public nombrepropioResponseBody() {
        }
        
        public nombrepropioResponseBody(string nombrepropioReturn) {
            this.nombrepropioReturn = nombrepropioReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoapServiceChannel : clientesoap.ServicioSOAP.SoapService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoapServiceClient : System.ServiceModel.ClientBase<clientesoap.ServicioSOAP.SoapService>, clientesoap.ServicioSOAP.SoapService {
        
        public SoapServiceClient() {
        }
        
        public SoapServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoapServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientesoap.ServicioSOAP.validarrutResponse clientesoap.ServicioSOAP.SoapService.validarrut(clientesoap.ServicioSOAP.validarrutRequest request) {
            return base.Channel.validarrut(request);
        }
        
        public string validarrut(string rut) {
            clientesoap.ServicioSOAP.validarrutRequest inValue = new clientesoap.ServicioSOAP.validarrutRequest();
            inValue.Body = new clientesoap.ServicioSOAP.validarrutRequestBody();
            inValue.Body.rut = rut;
            clientesoap.ServicioSOAP.validarrutResponse retVal = ((clientesoap.ServicioSOAP.SoapService)(this)).validarrut(inValue);
            return retVal.Body.validarrutReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clientesoap.ServicioSOAP.validarrutResponse> clientesoap.ServicioSOAP.SoapService.validarrutAsync(clientesoap.ServicioSOAP.validarrutRequest request) {
            return base.Channel.validarrutAsync(request);
        }
        
        public System.Threading.Tasks.Task<clientesoap.ServicioSOAP.validarrutResponse> validarrutAsync(string rut) {
            clientesoap.ServicioSOAP.validarrutRequest inValue = new clientesoap.ServicioSOAP.validarrutRequest();
            inValue.Body = new clientesoap.ServicioSOAP.validarrutRequestBody();
            inValue.Body.rut = rut;
            return ((clientesoap.ServicioSOAP.SoapService)(this)).validarrutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clientesoap.ServicioSOAP.nombrepropioResponse clientesoap.ServicioSOAP.SoapService.nombrepropio(clientesoap.ServicioSOAP.nombrepropioRequest request) {
            return base.Channel.nombrepropio(request);
        }
        
        public string nombrepropio(string nombres, string apellidopa, string apellidoma, string sexo) {
            clientesoap.ServicioSOAP.nombrepropioRequest inValue = new clientesoap.ServicioSOAP.nombrepropioRequest();
            inValue.Body = new clientesoap.ServicioSOAP.nombrepropioRequestBody();
            inValue.Body.nombres = nombres;
            inValue.Body.apellidopa = apellidopa;
            inValue.Body.apellidoma = apellidoma;
            inValue.Body.sexo = sexo;
            clientesoap.ServicioSOAP.nombrepropioResponse retVal = ((clientesoap.ServicioSOAP.SoapService)(this)).nombrepropio(inValue);
            return retVal.Body.nombrepropioReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<clientesoap.ServicioSOAP.nombrepropioResponse> clientesoap.ServicioSOAP.SoapService.nombrepropioAsync(clientesoap.ServicioSOAP.nombrepropioRequest request) {
            return base.Channel.nombrepropioAsync(request);
        }
        
        public System.Threading.Tasks.Task<clientesoap.ServicioSOAP.nombrepropioResponse> nombrepropioAsync(string nombres, string apellidopa, string apellidoma, string sexo) {
            clientesoap.ServicioSOAP.nombrepropioRequest inValue = new clientesoap.ServicioSOAP.nombrepropioRequest();
            inValue.Body = new clientesoap.ServicioSOAP.nombrepropioRequestBody();
            inValue.Body.nombres = nombres;
            inValue.Body.apellidopa = apellidopa;
            inValue.Body.apellidoma = apellidoma;
            inValue.Body.sexo = sexo;
            return ((clientesoap.ServicioSOAP.SoapService)(this)).nombrepropioAsync(inValue);
        }
    }
}
