//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://prueba", ConfigurationName="SOAP.redes")]
    public interface redes
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Rut del espacio de nombres http://prueba no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SOAP.validadigitoResponse validadigito(SOAP.validadigitoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP.validadigitoResponse> validadigitoAsync(SOAP.validadigitoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Rut del espacio de nombres http://prueba no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SOAP.validarutResponse validarut(SOAP.validarutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP.validarutResponse> validarutAsync(SOAP.validarutRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Nombres del espacio de nombres http://prueba no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SOAP.nombrepropioResponse nombrepropio(SOAP.nombrepropioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAP.nombrepropioResponse> nombrepropioAsync(SOAP.nombrepropioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validadigitoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validadigito", Namespace="http://prueba", Order=0)]
        public SOAP.validadigitoRequestBody Body;
        
        public validadigitoRequest()
        {
        }
        
        public validadigitoRequest(SOAP.validadigitoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://prueba")]
    public partial class validadigitoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Rut;
        
        public validadigitoRequestBody()
        {
        }
        
        public validadigitoRequestBody(string Rut)
        {
            this.Rut = Rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validadigitoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validadigitoResponse", Namespace="http://prueba", Order=0)]
        public SOAP.validadigitoResponseBody Body;
        
        public validadigitoResponse()
        {
        }
        
        public validadigitoResponse(SOAP.validadigitoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://prueba")]
    public partial class validadigitoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validadigitoReturn;
        
        public validadigitoResponseBody()
        {
        }
        
        public validadigitoResponseBody(string validadigitoReturn)
        {
            this.validadigitoReturn = validadigitoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarut", Namespace="http://prueba", Order=0)]
        public SOAP.validarutRequestBody Body;
        
        public validarutRequest()
        {
        }
        
        public validarutRequest(SOAP.validarutRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://prueba")]
    public partial class validarutRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Rut;
        
        public validarutRequestBody()
        {
        }
        
        public validarutRequestBody(string Rut)
        {
            this.Rut = Rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validarutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validarutResponse", Namespace="http://prueba", Order=0)]
        public SOAP.validarutResponseBody Body;
        
        public validarutResponse()
        {
        }
        
        public validarutResponse(SOAP.validarutResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://prueba")]
    public partial class validarutResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string validarutReturn;
        
        public validarutResponseBody()
        {
        }
        
        public validarutResponseBody(string validarutReturn)
        {
            this.validarutReturn = validarutReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nombrepropioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nombrepropio", Namespace="http://prueba", Order=0)]
        public SOAP.nombrepropioRequestBody Body;
        
        public nombrepropioRequest()
        {
        }
        
        public nombrepropioRequest(SOAP.nombrepropioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://prueba")]
    public partial class nombrepropioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ap_paterno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ap_materno;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Genero;
        
        public nombrepropioRequestBody()
        {
        }
        
        public nombrepropioRequestBody(string Nombres, string Ap_paterno, string Ap_materno, string Genero)
        {
            this.Nombres = Nombres;
            this.Ap_paterno = Ap_paterno;
            this.Ap_materno = Ap_materno;
            this.Genero = Genero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nombrepropioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="nombrepropioResponse", Namespace="http://prueba", Order=0)]
        public SOAP.nombrepropioResponseBody Body;
        
        public nombrepropioResponse()
        {
        }
        
        public nombrepropioResponse(SOAP.nombrepropioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://prueba")]
    public partial class nombrepropioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombrepropioReturn;
        
        public nombrepropioResponseBody()
        {
        }
        
        public nombrepropioResponseBody(string nombrepropioReturn)
        {
            this.nombrepropioReturn = nombrepropioReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface redesChannel : SOAP.redes, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class redesClient : System.ServiceModel.ClientBase<SOAP.redes>, SOAP.redes
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public redesClient() : 
                base(redesClient.GetDefaultBinding(), redesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.redes.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public redesClient(EndpointConfiguration endpointConfiguration) : 
                base(redesClient.GetBindingForEndpoint(endpointConfiguration), redesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public redesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(redesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public redesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(redesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public redesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP.validadigitoResponse SOAP.redes.validadigito(SOAP.validadigitoRequest request)
        {
            return base.Channel.validadigito(request);
        }
        
        public string validadigito(string Rut)
        {
            SOAP.validadigitoRequest inValue = new SOAP.validadigitoRequest();
            inValue.Body = new SOAP.validadigitoRequestBody();
            inValue.Body.Rut = Rut;
            SOAP.validadigitoResponse retVal = ((SOAP.redes)(this)).validadigito(inValue);
            return retVal.Body.validadigitoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP.validadigitoResponse> SOAP.redes.validadigitoAsync(SOAP.validadigitoRequest request)
        {
            return base.Channel.validadigitoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP.validadigitoResponse> validadigitoAsync(string Rut)
        {
            SOAP.validadigitoRequest inValue = new SOAP.validadigitoRequest();
            inValue.Body = new SOAP.validadigitoRequestBody();
            inValue.Body.Rut = Rut;
            return ((SOAP.redes)(this)).validadigitoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP.validarutResponse SOAP.redes.validarut(SOAP.validarutRequest request)
        {
            return base.Channel.validarut(request);
        }
        
        public string validarut(string Rut)
        {
            SOAP.validarutRequest inValue = new SOAP.validarutRequest();
            inValue.Body = new SOAP.validarutRequestBody();
            inValue.Body.Rut = Rut;
            SOAP.validarutResponse retVal = ((SOAP.redes)(this)).validarut(inValue);
            return retVal.Body.validarutReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP.validarutResponse> SOAP.redes.validarutAsync(SOAP.validarutRequest request)
        {
            return base.Channel.validarutAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP.validarutResponse> validarutAsync(string Rut)
        {
            SOAP.validarutRequest inValue = new SOAP.validarutRequest();
            inValue.Body = new SOAP.validarutRequestBody();
            inValue.Body.Rut = Rut;
            return ((SOAP.redes)(this)).validarutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAP.nombrepropioResponse SOAP.redes.nombrepropio(SOAP.nombrepropioRequest request)
        {
            return base.Channel.nombrepropio(request);
        }
        
        public string nombrepropio(string Nombres, string Ap_paterno, string Ap_materno, string Genero)
        {
            SOAP.nombrepropioRequest inValue = new SOAP.nombrepropioRequest();
            inValue.Body = new SOAP.nombrepropioRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Ap_paterno = Ap_paterno;
            inValue.Body.Ap_materno = Ap_materno;
            inValue.Body.Genero = Genero;
            SOAP.nombrepropioResponse retVal = ((SOAP.redes)(this)).nombrepropio(inValue);
            return retVal.Body.nombrepropioReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAP.nombrepropioResponse> SOAP.redes.nombrepropioAsync(SOAP.nombrepropioRequest request)
        {
            return base.Channel.nombrepropioAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAP.nombrepropioResponse> nombrepropioAsync(string Nombres, string Ap_paterno, string Ap_materno, string Genero)
        {
            SOAP.nombrepropioRequest inValue = new SOAP.nombrepropioRequest();
            inValue.Body = new SOAP.nombrepropioRequestBody();
            inValue.Body.Nombres = Nombres;
            inValue.Body.Ap_paterno = Ap_paterno;
            inValue.Body.Ap_materno = Ap_materno;
            inValue.Body.Genero = Genero;
            return ((SOAP.redes)(this)).nombrepropioAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.redes))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.redes))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/WebServiceProject/services/redes");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return redesClient.GetBindingForEndpoint(EndpointConfiguration.redes);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return redesClient.GetEndpointAddress(EndpointConfiguration.redes);
        }
        
        public enum EndpointConfiguration
        {
            
            redes,
        }
    }
}
